name: Daily NBA Bets Analysis

on:
  schedule:
    # 11:30 PM Pacific Standard Time / 07:30 UTC
    - cron: "15 8 * * *"
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sport: [nba]
      fail-fast: false
    name: ${{ matrix.sport }}-analysis
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Analysis
        env:
          API_KEY: ${{ secrets.API_KEY }}
          NFL_ANALYSIS_API_URL: ${{ secrets.NFL_ANALYSIS_API_URL }}
          NBA_ANALYSIS_API_URL: ${{ secrets.NBA_ANALYSIS_API_URL }}
          MLB_ANALYSIS_API_URL: ${{ secrets.MLB_ANALYSIS_API_URL }}
          WNBA_ANALYSIS_API_URL: ${{ secrets.WNBA_ANALYSIS_API_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: uv run -m daily_bets ${{ matrix.sport }}


